version: '3.7'
services:
  adminer:
    image: adminer:latest
    restart: on-failure
    ports:
      - '8080:8080'
  db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  nginx:
    image: nginx:1.17.9-alpine
    restart: on-failure
    volumes:
      - './MyCantineApp/public/:/user/src/app/'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .phpenv
  elk:
    image: willdurand/elk
    ports:
      - 81:80
    volumes:
      - ./elk/logstash:/etc/logstash
      - ./elk/logstash/patterns:/opt/logstash/patterns