version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
    volumes:
    - ./db/data/:/var/lib/myqsl
  php:
    build: ./docker/php
    restart: always
    ports:
      - '9000:9001'
    depends_on:
      - db
    volumes:
      - ./Youngfood/:/var/www/symfony:cached
  nginx:
    build: ./docker/nginx
    restart: always
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    depends_on:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./Youngfood/:/var/www/symfony:cached
  adminer:
    image: adminer:latest
    restart: always
    ports: ['8080:8080']
    depends_on:
      - db
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
  mercure:
    image: dunglas/mercure
    environment:
      - JWT_KEY=!InsecureChangeMe! # You have to change MERCURE_JWT_SECRET in api/.env when you change this. You can put the old value of MERCURE_JWT_SECRET into the debugger on https://jwt.io/ and put the new value of JWT_KEY in the "secret" field to obtain the new encoded value for MERCURE_JWT_SECRET
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
      - PUBLISH_ALLOWED_ORIGINS=http://localhost:1337,https://localhost:1338
      - DEMO=1
    ports:
      - "1337:80"